#!/bin/bash
urls=("https://www.google.com" "https://www.github.com" "https://www.stackoverflow.com")
chosen_input=$(printf '%s\n' "${urls[@]}" | rofi -dmenu -p "Choose URL or enter search term:")

if [ -n "$chosen_input" ]; then
    if [[ "$chosen_input" =~ ^https?:// ]]; then
        firefox "$chosen_input"
    else
        search_term=$(echo "$chosen_input" | sed 's/ /+/g')
        firefox "https://www.google.com/search?q=$search_term"
    fi
fi
